# Build manifest for sourcehut (https://builds.sr.ht/~gullik/cerulean)
image: archlinux

packages:
  - curl go-ipfs godot unzip

sources:
  - https://git.sr.ht/~gullik/cerulean

tasks:
  - sync_assets: |
      cd cerulean
      ipfs daemon --init --init-profile server > /dev/null 2>&1 &
      timeout 1000 sh -c 'while ! ipfs swarm peers > /dev/null 2>&1; do sleep 1; done'
      for file in $(find assets/ -type f | sort); do
        hash="$(cat "$file")"
        [ -n "$hash" ]
        timeout 1000 ipfs get --output="$file" "$hash" > /dev/null 2>&1
        [ "$(ipfs add --offline --only-hash --hash=sha2-512 --quiet "$file")" = "$hash" ]
      done
      kill "$!"

  - download_godot: |
      curl --silent --max-time 1000 --remote-name 'https://downloads.tuxfamily.org/godotengine/4.0/beta3/Godot_v4.0-beta3_linux.x86_64.zip'
      echo 'a5d3e6e33107f2cae272b459994cd0cb65e13a2d5e4e7f387dde9f815074999ecf23e3b3b8c2673f591bb97126a2376816c6dff7209f75645ff3c536fe603323  Godot_v4.0-beta3_linux.x86_64.zip' | sha512sum --check
      unzip Godot_v4.0-beta3_linux.x86_64.zip

  - export_game_pack: |
      cd cerulean
      sed -i "s/const GIT_HASH: String = \"\"/const GIT_HASH: String = \"$(git rev-parse HEAD)\"/g" src/constants/version.gd
      ../Godot_v4.0-beta3_linux.x86_64 --headless --editor --quit || true
      ../Godot_v4.0-beta3_linux.x86_64 --headless --export-pack Linux/X11 ../cerulean.pck || true
      cd ..
      sha512sum cerulean.pck | tee cerulean.pck.sha512

artifacts:
  - cerulean.pck
  - cerulean.pck.sha512
