# Build manifest for sourcehut (https://builds.sr.ht/~gullik/cerulean)
image: archlinux

packages:
  - curl go-ipfs godot unzip

sources:
  - https://git.sr.ht/~gullik/cerulean

tasks:
  - sync_assets: |
      cd cerulean
      ipfs init
      for file in $(find assets -type f | sort); do
        hash="$(cat $file)"
        curl --silent --max-time 600 "https://cloudflare-ipfs.com/ipfs/$hash" | tee "$file" | ipfs add --offline --only-hash --hash=sha2-512 --quiet | grep "^$hash$" \
          || curl --silent --max-time 600 "https://gateway.pinata.cloud/ipfs/$hash" | tee "$file" | ipfs add --offline --only-hash --hash=sha2-512 --quiet | grep "^$hash$" \
          || curl --silent --max-time 600 "https://ipfs.io/ipfs/$hash" | tee "$file" | ipfs add --offline --only-hash --hash=sha2-512 --quiet | grep "^$hash$" \
          || exit 1
      done

  - download_godot: |
      curl --silent --max-time 600 --remote-name https://downloads.tuxfamily.org/godotengine/4.0/alpha15/Godot_v4.0-alpha15_linux.x86_64.zip
      echo 'd67cce8a6240f2b24fce090a69f4f47cb71b8de9a64a2ff4ea128bf319624b52dbf69a5955bfb7a00b05856b74108012770bb451a6d214449e44e99d01e215f0  Godot_v4.0-alpha15_linux.x86_64.zip' | sha512sum --check
      unzip Godot_v4.0-alpha15_linux.x86_64.zip

  - export_game_pack: |
      cd cerulean
      sed -i "s/const GIT_HASH: String = \"\"/const GIT_HASH: String = \"$(git rev-parse HEAD)\"/g" src/constants/version.gd
      ../Godot_v4.0-alpha15_linux.x86_64 --headless --editor --quit || true
      ../Godot_v4.0-alpha15_linux.x86_64 --headless --export-pack Linux/X11 ../cerulean.pck || true
      cd ..
      sha512sum cerulean.pck | tee cerulean.pck.sha512

artifacts:
  - cerulean.pck
  - cerulean.pck.sha512
