# Build manifest for sourcehut (https://builds.sr.ht/~gullik/cerulean)
image: archlinux

packages:
  - curl go-ipfs godot unzip

sources:
  - https://git.sr.ht/~gullik/cerulean

tasks:
  - sync_assets: |
      cd cerulean
      ipfs init
      for file in $(find assets -type f | sort); do
        hash="$(cat $file)"
        curl --silent --max-time 600 "https://cloudflare-ipfs.com/ipfs/$hash" | tee "$file" | ipfs add --offline --only-hash --hash=sha2-512 --quiet | grep "^$hash$" \
          || curl --silent --max-time 600 "https://gateway.pinata.cloud/ipfs/$hash" | tee "$file" | ipfs add --offline --only-hash --hash=sha2-512 --quiet | grep "^$hash$" \
          || curl --silent --max-time 600 "https://ipfs.io/ipfs/$hash" | tee "$file" | ipfs add --offline --only-hash --hash=sha2-512 --quiet | grep "^$hash$" \
          || exit 1
      done

  - download_godot: |
      curl --silent --max-time 600 --remote-name https://downloads.tuxfamily.org/godotengine/4.0/alpha14/Godot_v4.0-alpha14_linux.64.zip
      echo 'c120ef59533c172ef71de2965de1e30d28955c07eb9e3debf2d413640072a86896a4bf7b73f841a0fa9ae2dd3674609089111e35dcf9b8b6690d82d8c6d7d2e4  Godot_v4.0-alpha14_linux.64.zip' | sha512sum --check
      unzip Godot_v4.0-alpha14_linux.64.zip

  - export_game_pack: |
      cd cerulean
      sed -i "s/const GIT_HASH: String = \"\"/const GIT_HASH: String = \"$(git rev-parse HEAD)\"/g" src/constants/version.gd
      ../Godot_v4.0-alpha14_linux.64 --headless --editor --quit || true
      ../Godot_v4.0-alpha14_linux.64 --headless --export-pack Linux/X11 ../cerulean.pck || true
      cd ..
      sha512sum cerulean.pck | tee cerulean.pck.sha512

artifacts:
  - cerulean.pck
  - cerulean.pck.sha512
