# Build manifest for sourcehut (https://builds.sr.ht/~gullik/cerulean)
image: archlinux

packages:
  - curl go-ipfs godot unzip

sources:
  - https://git.sr.ht/~gullik/cerulean

tasks:
  - sync_assets: |
      cd cerulean
      ipfs init
      for file in $(find assets -type f | sort); do
        hash="$(cat $file)"
        curl --silent --max-time 600 "https://cloudflare-ipfs.com/ipfs/$hash" | tee "$file" | ipfs add --offline --only-hash --hash=sha2-512 --quiet | grep "^$hash$" \
          || curl --silent --max-time 600 "https://gateway.pinata.cloud/ipfs/$hash" | tee "$file" | ipfs add --offline --only-hash --hash=sha2-512 --quiet | grep "^$hash$" \
          || curl --silent --max-time 600 "https://ipfs.io/ipfs/$hash" | tee "$file" | ipfs add --offline --only-hash --hash=sha2-512 --quiet | grep "^$hash$" \
          || exit 1
      done

  - download_godot: |
      curl --silent --max-time 600 --remote-name https://downloads.tuxfamily.org/godotengine/4.0/beta1/Godot_v4.0-beta1_linux.x86_64.zip
      echo 'de06dfaa0240d49c3dc8dec21551486ccf3fab36adab780e06d846621a3f7dc6871c57a6dde08a13b96e6cf7f9c5dd65485b76a6ae1b6f66cc8878de49b9a8cd  Godot_v4.0-beta1_linux.x86_64.zip' | sha512sum --check
      unzip Godot_v4.0-beta1_linux.x86_64.zip

  - export_game_pack: |
      cd cerulean
      sed -i "s/const GIT_HASH: String = \"\"/const GIT_HASH: String = \"$(git rev-parse HEAD)\"/g" src/constants/version.gd
      ../Godot_v4.0-beta1_linux.x86_64 --headless --editor --quit || true
      ../Godot_v4.0-beta1_linux.x86_64 --headless --export-pack Linux/X11 ../cerulean.pck || true
      cd ..
      sha512sum cerulean.pck | tee cerulean.pck.sha512

artifacts:
  - cerulean.pck
  - cerulean.pck.sha512
