# Build manifest for sourcehut (https://builds.sr.ht/~gullik/cerulean)
image: alpine/latest

packages:
  - curl

sources:
  - https://git.sr.ht/~gullik/cerulean

tasks:
  - check_asset_availability: |
      cd cerulean
      for file in $(find assets -type f | sort); do
        hash=$(cat $file)
        curl --head --silent --fail --max-time 10 --output /dev/null https://ipfs.io/ipfs/$hash || exit 1
      done
