# Build manifest for sourcehut (https://builds.sr.ht/~gullik/cerulean)
image: archlinux

packages:
  - curl git kubo unzip

sources:
  - https://git.sr.ht/~gullik/cerulean

tasks:
  - sync_assets: |
      cd cerulean
      ipfs daemon --init --init-profile server > /dev/null 2>&1 &
      timeout --verbose 1000 sh -c 'while ! ipfs swarm peers > /dev/null 2>&1; do sleep 1; done'
      git config --local include.path ../.gitconfig
      rm -rf assets
      timeout --verbose 1000 git reset --hard
      kill "$!"

  - download_godot: |
      timeout --verbose 1000 curl --silent --remote-name 'https://downloads.tuxfamily.org/godotengine/4.0/rc2/Godot_v4.0-rc2_linux.x86_64.zip'
      echo 'e97fda1e44ed30ad14607731ad096a91da8bf803ff193466dce6493cb5acb796754455140d31b20315994f724f9dc8e7985d9901933cf8742209eb35744a6fb3  Godot_v4.0-rc2_linux.x86_64.zip' | sha512sum --check
      unzip Godot_v4.0-rc2_linux.x86_64.zip

  - export_game_pack: |
      cd cerulean
      sed -i "s/const GIT_HASH: String = \"\"/const GIT_HASH: String = \"$(git rev-parse HEAD)\"/g" src/constants/version.gd
      timeout --verbose 1000 sh -c '../Godot_v4.0-rc2_linux.x86_64 --headless --editor --quit || true'
      timeout --verbose 1000 sh -c '../Godot_v4.0-rc2_linux.x86_64 --headless --export-pack Linux/X11 ../cerulean.pck || true'
      cd ..
      sha512sum cerulean.pck | tee cerulean.pck.sha512

artifacts:
  - cerulean.pck
  - cerulean.pck.sha512
