# Build manifest for sourcehut (https://builds.sr.ht/~gullik/cerulean)
image: archlinux

packages:
  - curl git godot kubo unzip

sources:
  - https://git.sr.ht/~gullik/cerulean

tasks:
  - sync_assets: |
      cd cerulean
      ipfs daemon --init --init-profile server > /dev/null 2>&1 &
      timeout 1000 sh -c 'while ! ipfs swarm peers > /dev/null 2>&1; do sleep 1; done'
      git config --local include.path ../.gitconfig
      rm -rf assets
      timeout 1000 git reset --hard
      kill "$!"

  - download_godot: |
      curl --silent --max-time 1000 --remote-name 'https://downloads.tuxfamily.org/godotengine/4.0/beta7/Godot_v4.0-beta7_linux.x86_64.zip'
      echo 'de83279874806a18719a8641e199e513fe09d63f4a87f9e6935daddadd50db650d873b21e045124da076d542f25c3b435459e326809185a71175a294db7b88a8  Godot_v4.0-beta7_linux.x86_64.zip' | sha512sum --check
      unzip Godot_v4.0-beta7_linux.x86_64.zip

  - export_game_pack: |
      cd cerulean
      sed -i "s/const GIT_HASH: String = \"\"/const GIT_HASH: String = \"$(git rev-parse HEAD)\"/g" src/constants/version.gd
      timeout 1000 sh -c '../Godot_v4.0-beta7_linux.x86_64 --headless --editor --quit || true'
      timeout 1000 sh -c '../Godot_v4.0-beta7_linux.x86_64 --headless --export-pack Linux/X11 ../cerulean.pck || true'
      cd ..
      sha512sum cerulean.pck | tee cerulean.pck.sha512

artifacts:
  - cerulean.pck
  - cerulean.pck.sha512
