# Build manifest for sourcehut (https://builds.sr.ht/~gullik/cerulean)
image: archlinux

packages:
  - curl go-ipfs godot unzip

sources:
  - https://git.sr.ht/~gullik/cerulean

tasks:
  - sync_assets: |
      cd cerulean
      ipfs daemon --init --init-profile server > /dev/null 2>&1 &
      timeout 1000 sh -c 'while ! ipfs swarm peers > /dev/null 2>&1; do sleep 1; done'
      for file in $(find assets/ -type f | sort); do
        hash="$(cat "$file")"
        [ -n "$hash" ]
        timeout 1000 ipfs get --output="$file" "$hash" > /dev/null 2>&1
        [ "$(ipfs add --offline --only-hash --hash=sha2-512 --quiet "$file")" = "$hash" ]
      done
      kill "$!"

  - download_godot: |
      curl --silent --max-time 1000 --remote-name 'https://downloads.tuxfamily.org/godotengine/4.0/beta6/Godot_v4.0-beta6_linux.x86_64.zip'
      echo '47995403b38ae0967499b4530eb7c65a8f61d544f19eb350388e9fea86e42eeb9136ce35e8d5e4ae07c22bbc47dc46a52b706000d8509cab156812a21c46c491  Godot_v4.0-beta6_linux.x86_64.zip' | sha512sum --check
      unzip Godot_v4.0-beta6_linux.x86_64.zip

  - export_game_pack: |
      cd cerulean
      sed -i "s/const GIT_HASH: String = \"\"/const GIT_HASH: String = \"$(git rev-parse HEAD)\"/g" src/constants/version.gd
      ../Godot_v4.0-beta6_linux.x86_64 --headless --editor --quit || true
      ../Godot_v4.0-beta6_linux.x86_64 --headless --export-pack Linux/X11 ../cerulean.pck || true
      cd ..
      sha512sum cerulean.pck | tee cerulean.pck.sha512

artifacts:
  - cerulean.pck
  - cerulean.pck.sha512
