# Build manifest for sourcehut (https://builds.sr.ht/~gullik/cerulean)
image: archlinux

packages:
  - curl git kubo unzip

sources:
  - https://git.sr.ht/~gullik/cerulean

tasks:
  - sync_assets: |
      cd cerulean
      ipfs daemon --init --init-profile server > /dev/null 2>&1 &
      timeout --verbose 1000 sh -c 'while ! ipfs swarm peers > /dev/null 2>&1; do sleep 1; done'
      git config --local include.path ../.gitconfig
      rm -rf assets
      timeout --verbose 1000 git reset --hard
      kill "$!"

  - download_godot: |
      timeout --verbose 1000 curl --silent --remote-name 'https://downloads.tuxfamily.org/godotengine/4.0.3/Godot_v4.0.3-stable_linux.x86_64.zip'
      echo '56a41dfdf96e20b015a9d9b245fb91bfbb13add62d7eabb377282a1ea15b6043a6aa59800cba08fcd3c5c2bca9bf3a499b0e18a6ccb9d22b514d86f7c6528bd4  Godot_v4.0.3-stable_linux.x86_64.zip' | sha512sum --check
      unzip Godot_v4.0.3-stable_linux.x86_64.zip

  - export_game_pack: |
      cd cerulean
      sed -i "s/const GIT_HASH: String = \"\"/const GIT_HASH: String = \"$(git rev-parse HEAD)\"/g" src/constants/version.gd
      timeout --verbose 1000 sh -c '../Godot_v4.0.3-stable_linux.x86_64 --headless --editor --quit || true'
      timeout --verbose 1000 sh -c '../Godot_v4.0.3-stable_linux.x86_64 --headless --export-pack Linux/X11 ../cerulean.pck || true'
      cd ..
      sha512sum cerulean.pck | tee cerulean.pck.sha512

artifacts:
  - cerulean.pck
  - cerulean.pck.sha512
